#! /usr/bin/env zsh
echo "Album  [optional]: "
read input
[[ -n $input ]] && album="-l $input" || album=""
echo "Artist [optional]: "
read input
[[ -n $input ]] && artist="-a $input" || artist=""
echo "Year   [optional]: "
read input
[[ -n $input ]] && year="-y $input" || year=""
echo "Genre  [optional]: "
read input
[[ -n $input ]] && genre="-g $input" || genre=""
mkdir temp
cd temp
youtube-dl -x --audio-format mp3 --console-title -f bestaudio $1
for i in *.mp3
do
  mp3info -i $artist $album $year $genre $i
  mv $i ../
done
cd ..
rm -rf temp/
