#!/bin/sh
[ "$1" = "1" ] && echo "Turning on tab on TrackPoint" && echo -n 1 > /sys/devices/platform/i8042/serio1/serio2/press_to_select && exit 0
[ "$1" = "0" ] && echo "Turning off tab on TrackPoint" && echo -n 0 > /sys/devices/platform/i8042/serio1/serio2/press_to_select && exit 0
echo -n "Tap status: "
cat /sys/devices/platform/i8042/serio1/serio2/press_to_select
